### ISSUE TITLE
A single chart to consolidate multiple charts.

### ISSUE THREAD

**Issue by digihunch** [digihunch/korthweb#6]
Istio requires [multiple charts](https://www.digihunch.com/2021/12/from-ingress-to-gateway-why-you-need-istio-gateways-on-kubernetes-platforms/) to complete install. we should have a single chart that consolidates all different charts

**Comment by digihunch** [comment]
for the parent chart, the Chart.yaml should contain the followings:
```yaml
dependencies:
  - name: base
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.12.x
    tags:
    - istio-base
  - name: istiod
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.12.x
    tags:
    - istiod
  - name: gateway
    alias: ingress-gateway
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.12.x
    tags:
    - istioingressgateway
  - name: gateway
    alias: egress-gateway
    repository: https://istio-release.storage.googleapis.com/charts
    version: 1.12.x
    tags:
    - istioegressgateway
```
and the values.yaml contains:
```yaml
istiod:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
ingress-gateway:
  name: istio-ingressgateway
  service:
    type: LoadBalancer
    ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15020
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: dicom
      port: 11112
      protocol: TCP
      targetPort: 4242
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "suitable-porpoise-lb-subnet"
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  nodeSelector:
    beta.kubernetes.io/os: linux
egress-gateway:
  name: istio-egressgateway
  service:
    type: ClusterIP
  labels:
    app: istio-egressgateway
    istio: egressgateway
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
  nodeSelector:
    beta.kubernetes.io/os: linux
```

This is kept in commit 8e010e8563a2459698c236ac1acd22fb3f357647 but it is not working due to a [limitation](https://github.com/helm/helm/issues/10392) with Helm's ability to reference two dependencies with the same URL. 
Therefore the directory will be deleted.
